--------------------------------------------------------
--  File created - Monday-August-24-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "TESTDB"."COMPANY" 
   (	"COMPANY" VARCHAR2(200 BYTE), 
	"COMPANYID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.COMPANY
SET DEFINE OFF;
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Listenin'' Booth',1);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Brooks Fashions',2);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fragrant Flower Lawn Services',3);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Atlas Realty',4);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crafts Canada',5);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Polk Brothers',6);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Full Color',7);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Coast to Coast Hardware',8);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Prestigabiz',9);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Manning''s Cafeterias',10);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lechmere',11);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Lawn Guru',12);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Quickbiz',13);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Schweggmanns',14);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big Daddy''s Restaurants',15);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Greenwich IGA',16);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bresler''s Ice Cream',17);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tons O'' Toys',18);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sambo''s',19);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Terra Nova Garden Services',20);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Yesterday''s Records',21);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Raleigh''s',22);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wag''s',23);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ruehl No. 925',24);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Harvest Foods',25);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Life''s Gold',26);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strong Life',27);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Compact Disc Center',28);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('KG Menswear',29);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Joseph Magnin',30);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Platinum Interior Design',31);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Peter Reeves',32);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Champion Auto',33);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Merrymaking',34);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fit Tonic',35);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gas Legion',36);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Klopfenstein''s',37);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Plunkett Home Furnishings',38);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Independent Planners',39);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Muscle Factory',40);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mighty Casey''s',41);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Weathervane',42);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Waccamaw''s Homeplace',43);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Price Savers',44);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wells & Wade',45);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rhodes Furniture',46);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('AJ Bayless',47);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sound Warehouse',48);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nelson Brothers',49);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('PriceRite Warehouse Club',50);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strategy Consulting',51);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Opticomp',52);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('TheBottomHalf',53);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Record & Tape Outlet',54);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lionel Playworld',55);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Yardbirds Home Center',56);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Turtle''s Records & Tapes',57);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk Home Loans',58);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('H. J. Wilson & Company',59);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Naturohair',60);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Back To Basics Chiropractic Clinic',61);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Silo',62);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Baltimore Markets',63);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Protean',64);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Super Place',65);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Giant Open Air',66);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('A+ Electronics',67);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Envirotecture Design Service',68);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Alexander''s',69);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Atlas Architectural Designs',70);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Alert Alarm Company',71);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Multi Tech Development',72);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ideal Garden Maintenance',73);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values (null,74);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('CompuAdd',75);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rich and Happy',76);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('First Rate Choice',77);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Video Concepts',78);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Food Mart',79);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strongbod',80);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Modern Realty',81);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gemco',82);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mages',83);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Flagg Bros. Shoes',84);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Weatherill''s',85);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lone Wolf Wealth Planning',86);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Multi-Systems Merchant Services',87);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('W. Bell & Co.',88);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Franklin Music',89);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('GEX',90);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Target Realty',91);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Audio Visions',92);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fedco',93);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Builderama',94);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Great Western',95);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Paul''s Record Hut',96);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big Wheel',97);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Little Tavern',98);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Excella',99);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Price''s Electronics',100);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Piece Goods Fabric',101);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Team Electronics',102);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Life Plan Counselling',103);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kelsey''s Neighbourhood Bar & Grill',104);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Super Saver Foods',105);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('AdventureSports!',106);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Goose and Duck',107);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Morrie Mages',108);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('One-Up Realtors',109);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('10000 Auto Parts',110);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Adray',111);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Foreman & Clark',112);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Infinite Wealth',113);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('China Coast',114);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Express Merchant Service',115);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Argus Tapes & Records',116);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Record World',117);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Paul Harris',118);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Road Runner Lawn Services',119);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kids Mart',120);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sofa Express',121);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Packer',122);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Furrow''s',123);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Integra Design',124);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('E-zhe Source',125);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mikro Designs',126);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Our Own Hardware',127);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asiatic Solutions',128);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Warner Brothers Store',129);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chase Pitkin',130);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Food Barn',131);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Galyan''s',132);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Eden Lawn Service',133);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('MacMarr Stores',134);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gene Walter''s Marketplace',135);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thorofare',136);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monmax',137);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Present Company',138);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magna Solution',139);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tweeter',140);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Eagle Food Centers',141);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Golden''s Distributors',142);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('World of Fun',143);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cellophane Square',144);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buena Vista Garden Maintenance',145);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Circuit Design',146);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gallenkamp',147);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('McDade''s',148);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Noodle Kidoodle',149);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gamma Gas',150);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ransohoffs',151);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Schucks Auto Supply',152);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Macroserve',153);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sholl''s Colonial Cafeteria',154);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Independent Wealth Management',155);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Martin''s',156);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Galaxy Man',157);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cut Above',158);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pioneer Chicken',159);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lafayette Radio',160);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wilson''s Jewelers',161);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pointers',162);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Star Assistance',163);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Funtown toys',164);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Megatronic',165);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Owl',166);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Frame Scene',167);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Auto Parts',168);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magik Gray',169);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Personal & Corporate Design',170);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Huyler''s',171);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('J. Brannam',172);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Enrich Garden Services',173);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('System Star',174);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('A. L. Price',175);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Virgin Megastores',176);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Western Auto',177);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('JumboSports',178);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Zany Brainy',179);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Paper Cutter',180);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Geri''s Hamburgers',181);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Garden Master',182);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr. AG''s',183);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jitney Jungle',184);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Unity Stationers',185);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ellman''s Catalog Showrooms',186);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Locost Accessories',187);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The High Heelers',188);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Plan Smart Partner',189);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wild Oats Markets',190);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Second Time Around',191);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Soul Sounds Unlimited',192);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Friendly Interior Design',193);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Starship Tapes & Records',194);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Independent Investors',195);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sounds Great Inc',196);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dreamscape Garden Care',197);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('ManCharm',198);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Skaggs-Alpha Beta',199);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Liberal',200);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Childrens Bargain Town',201);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Realty Solution',202);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Peaches',203);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chandlers',204);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Super Duper',205);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Loblaws',206);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Linens ''n Things',207);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Netstars Matrix Design',208);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Helping Hand',209);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hugh M. Woods',210);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('K&G Distributors',211);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Parts America',212);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('White Tower Hamburgers',213);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Just For Fun',214);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pomeroy''s',215);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Brendle''s',216);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grass Roots Yard Services',217);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Eli Moore Inc',218);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Laneco',219);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Garden Guru',220);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Saturday Matinee',221);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Angel''s',222);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Plan Future',223);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Frank''s Nursery & Crafts',224);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Elm Farm',225);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Matrix Interior Design',226);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Avant Garde Appraisal',227);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gamble-Skogmo',228);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pearl Architectural Design',229);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Laura Ashley Mother & Child',230);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big A Auto Parts',231);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Almacs',232);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Choices',234);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Edge Garden Services',235);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hamady Bros. Supermarkets',236);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Delchamps',238);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jacobs',240);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Polka Dot Bear Tavern',241);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('William Wanamaker & Sons',242);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Adaptas',243);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jay Jacobs',245);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big D Supermarkets',246);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Boys Markets',247);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Freedom Map',249);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Vinyl Fever',250);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Handyman',251);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rainbow Bay Crafts',253);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bodega Club',254);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Canal Villere',255);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Museum Company',256);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Best Biz Survis',257);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Listen Up',259);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Janeville',260);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Prahject Planner',261);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Herman''s World of Sporting Goods',262);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rickel',263);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Shoe Kicks',266);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Future Bright',267);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Whitlocks Auto Supply',268);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lee Wards',271);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Destiny Planners',272);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sunny''s Surplus',274);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Network Development',275);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gino''s Hamburgers',277);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Oklahoma Tire & Supply Company',278);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cala Foods',280);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Solution Answers',281);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Coconut''s',282);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magna Gases',284);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Star Interior Design',285);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Realty Depot',286);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Food',289);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tech Hifi',291);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Good Guys',293);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Irving''s Sporting Goods',294);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('DGS HomeSource',296);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Market Basket',297);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Circuit City',298);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('MVP Sports',300);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sunny Real Estate Investments',301);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magik Lamp',302);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('King Carol',303);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Purity',304);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Expo Superstore',306);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kash n'' Karry',308);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Intelli Wealth Group',309);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('KB Toys',310);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('id Boutiques',312);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lawn N'' Order Garden Care',313);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Environ Architectural Design',315);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magik Grey',317);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gold Touch',318);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('J. B. Van Sciver',319);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Standard Brands Paint Company',320);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Fox and Hound ',321);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro Star',323);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hechinger',325);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Belle Lady',326);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Integra Investment Plan',327);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Exact Solutions',328);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asian Fusion',329);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Singer Lumber',331);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Prestiga-Biz',332);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Two Pesos',334);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('StopGrey',335);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Enviro Architectural Designs',336);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr. Good Buys',337);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Orion',339);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sandy''s',340);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hoyden',341);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Block Distributors',342);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bell Markets',343);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Egghead Software',344);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Budget Tapes & Records',346);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Maxi-Tech',348);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('York Steak House',349);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Budget Power',350);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('L.L. Berger',351);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Integra Wealth Planners',352);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Endicott Johnson',353);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Security Sporting Goods',354);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buttrey Food & Drug',355);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tam''s Stationers',356);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thompson',357);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Laura Ashley',358);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Family Toy',359);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nutri G',360);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Custom Lawn Care',361);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Harold''s',362);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Forth & Towne',363);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Life Map',364);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Target Source',365);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ernst Home Centers',366);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lionel Kiddie City',367);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Your Future Is Now',368);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wherehouse Music',369);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('House Works',370);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fisher Foods',371);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lechters Housewares',372);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dynatronics Accessories',373);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Matrix Architectural Service',374);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Aaronson Furniture',375);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Warshal''s',376);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Today''s Man',377);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Adaptabiz',378);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Wiz',379);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Walt''s IGA',380);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Formula Grey',381);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Maurice The Pants Man',382);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Corpbay',383);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monsource',384);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Planetbiz',385);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk Home Funding Services',386);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Exact Realty',387);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pacific Stereo',388);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rogers Food Stores',389);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Zephyr Investments',390);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Plan Smart',391);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Affinity Investment Group',392);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Baron Electronics',393);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Twin Food Stores',394);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lawnscape Garden Maintenance',395);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bettendorf''s',396);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sports Town USA',397);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pup ''N'' Taco',398);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Computer City',399);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tower Records',400);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Knockout Kickboxing',401);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Edge Yard Service',402);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Forum Cafeterias',403);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Afforda Merchant Services',404);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Vari-Tec',405);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Infinite Wealth Planners',406);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Royal Gas',407);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Standard Food',408);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gamma Realty',409);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Robert Hall',410);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Merry-Go-Round',411);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Scott Ties',412);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jackpot Consultant',413);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Music Plus',414);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr Fables',415);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Komerci',416);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Beefsteak Charlie''s',417);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Williams Bros.',418);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Frank and Seder',419);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Waccamaw Pottery',420);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Olympic Sports',421);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Las Vegas Yard Management',422);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Electric Avenue',423);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sew-Fro Fabrics',424);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Miller & Rhoads',425);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Castle Realty',426);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Body Toning',427);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Happy Bear Investment',428);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Your Choices',429);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rustler Steak House',430);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lum''s',431);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Practi-Plan Mapping',432);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Manu Connection',433);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dave Cooks',434);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Prospa-Pal',435);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Formula Gray',436);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Practi-Plan',437);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('MagnaSolution',438);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Foxmoor',439);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cut Rite',440);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Electronics Source',441);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Steinberg''s',442);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Maxiserve ',443);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro-Care Garden Maintenance',444);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Home Centers',445);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ole''s',446);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Alpha Beta',447);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Central Hardware',448);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Leonard Krower & Sons',449);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Steve & Barry''s',450);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Maxaprofit',451);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Midwest TV & Appliance',452);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rex Audio Video Appliance',453);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Levitz Furniture',454);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Burstein-Applebee',455);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Johnson''s General Stores',456);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Old America Stores',457);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Builders Square',458);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Superior Appraisals',459);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Trak Auto',460);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buena Vista Realty Service',461);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pay''N Takeit',462);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sanitary Grocery Stores',463);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Anthony''s',464);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asian Solutions',465);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('L'' Fish',466);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ejecta',467);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk Home Improvements',468);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Matrix Architectural Service ',469);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rossi Auto Parts',470);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Metro',471);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Krauses Sofa Factory',472);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Beatties',473);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk Real Estate Service',474);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Techo Solutions',475);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Erol''s',476);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Leo''s Stereo',477);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Acuserv',478);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Beasts of Beauty',479);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Star Merchant Services',480);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dream Home Improvements',481);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sistemos',482);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Discount Furniture Showcase',483);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hanover Shoe',484);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('House of Gas',485);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Eagle Hardware & Garden',486);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lindsley''s Lumber',487);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Xray Eye & Vision Clinics',488);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Universo Realtors',489);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('BASCO',490);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Littler''s',491);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Great Train Stores',492);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Netobill',493);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Flying Hippo ',494);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Liberty Wealth Planners',495);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('On Cue',496);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('SoundTrack',497);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mostow Co.',498);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Desert Garden Help',499);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grey Fade',500);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ukrop''s Super Market',501);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Advansed Teksyztems',502);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Heslop''s',503);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Edwards',504);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Robin Stores',505);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Endicott Shoes',506);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monlinks',507);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('John F. Lawhon',508);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Matrix Design',509);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Children''s Palace',510);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Avant Garde Interior Designs',511);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gov Mart',512);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sportmart',513);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rose Records',514);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Bears Tavern',515);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Parts and Pieces',516);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jafco',517);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Envirotecture Design',518);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bountiful Harvest Health Food Store',519);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chess King',520);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Liberty Wealth Planner',521);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crazy Tiger',522);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Oshman''s',523);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sam Goody',524);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Purity Supreme',525);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The White Rabbit',526);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('All Wound Up',527);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('You Are Successful',528);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Simply Appraisals',529);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Morrison''s Cafeteria',530);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Reliable Garden Management',531);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Clemens Markets',532);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chandler''s',533);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bold Ideas',534);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wickes Furniture',535);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fireball',536);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Yard Maintenance',537);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Olson Electronics',538);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Service Merchandise',539);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Maloley''s Finer Foods',540);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Planet Pizza',541);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grossman''s',542);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('De Pinna',543);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Spotted Cougar',544);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Borders Books',545);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Yard Management',546);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jackhammer Technologies',547);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Suncoast Video',548);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wealth Zone Group',549);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Harmony House',550);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Brown Derby',551);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Shoe Pavilion',552);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grodins',553);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hughes Markets',554);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crazy Eddie',555);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Perisolution',556);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Capitalcorp',557);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Solid Future',559);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Quality Merchant Services',560);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Royal Canadian Pancake Houses',561);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Playworld',562);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Opti-Tek',564);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rivera Property Maintenance',566);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('County Market',568);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Montana''s Cookhouse',569);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Weingarten''s',570);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('First Choice Yard Help',571);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dee''s Drive-In',573);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('A.J. August Fashion Wear',574);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bombay Company',575);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Colonial Stores',576);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Record Town',578);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Creative Wealth',579);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Greyvoid',582);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Integra Investment Service',583);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('STM Auto Parts',585);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Record Mart',587);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Beaver Lumber',588);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Del Farm',591);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Deco Refreshments Inc.',592);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pender''s Food Stores',593);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kohl''s Food Stores',594);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Avant Garde Appraisal Group',596);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('McMahan''s Furniture',598);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Northern Reflections',599);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Alladin Realty',600);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Blockbuster Music',602);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Hardgoods Distributors',603);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('d.e.m.o.',604);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Blue Boar Cafeterias',606);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Veramons',607);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('J. K. Gill Company',608);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Builders Emporium',609);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Netaid',610);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Jolly Farmer',612);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sunburst Garden Management',613);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Holly Tree Inn',614);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('White Coffee Pot',615);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Keeney''s',617);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kessel Food Market',618);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Value Giant',619);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Club Wholesale',620);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Destiny Realty Solutions',622);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Datacorp',623);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pace Membership Warehouse',624);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Disc Jockey',626);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kelly and Cohen',627);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buck Alley Lumber',628);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Highland Appliance',629);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wise Appraisals',630);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Courtesy Hardware Store',632);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jewel Mart',634);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Audio Aid',635);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Romp',636);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Earl Abel''s',637);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Tea',638);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('La Petite Boulangerie',640);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Patterson-Fletcher',641);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buehler Foods',642);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Landskip Yard Care',643);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Friendly Advice',644);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Twin Electronics',645);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('System Star Solutions',648);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jacob Reed and Sons',649);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hollywood Video',651);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nobil',652);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rite Solution',653);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asian Answers',654);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Best Products',655);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Creative Wealth Management',656);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Casual Corner',658);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gantos',659);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tee Town',660);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Record Shops at TSS',662);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Belle Ladi',664);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Handy City',666);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hit or Miss',668);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Penn Fruit',669);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Food Giant',671);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gart Sports',672);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Child World',673);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('University Stereo',674);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fradkin Brothers Furniture',675);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Little Folk Shops',677);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('I. Magnin',678);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Multicerv',680);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ardan''s',681);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Farmer Jack',682);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sammy''s Record Shack',683);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Webcom Business Services',684);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Waves Music',687);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sav-A-Center',688);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Isaly''s',691);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Lumber',692);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Madcats Music & Books',693);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Albers Super Markets',694);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('New World',695);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Harold Powell',696);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Forest City',697);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Circus World',698);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Consumers and Consumers Express',699);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mikrotechnic',700);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Star Bright Investment Group',701);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Awthentikz',702);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Serve',703);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('John Plain',704);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Country Club Markets',705);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dream Home Real Estate Service',706);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stop and Shop',707);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('National Shirt Shop',708);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pantry Food Stores',709);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Super Shops',710);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Media Play',711);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Henry''s Hamburgers',712);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stratapro',713);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Realty Zone',714);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Poore Simon''s',715);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grand Union',716);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('JasmineSola',717);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Century House',718);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bugle Boy',719);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('White Hen Pantry',720);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wheels Discount Auto',721);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Silverwoods',722);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Red Fox Tavern',723);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Standard Sales',724);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Complete Tech',725);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mission You',726);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Great American Music',727);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nan Duskin',728);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('De-Jaiz Mens Clothing',729);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fayva',730);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Just For Feet',731);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asian Junction',732);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Earthworks Garden Kare',733);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Eisner Food Stores',734);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Tech Solutions',735);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Handy Andy Home Improvement Center',736);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sherman''s',737);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pleasures and Pasttimes',738);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strategy Planner',739);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rink''s',740);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Action Auto',741);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Roberd''s',742);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Griff''s Hamburgers',743);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr. Clark''s Appliances',744);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Success Is Yours',745);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stratacard',746);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('AM/PM Camp',747);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Golden Dawn',748);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Shabby Chic',749);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('EnviroSource Design',750);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Serendipity Dip',751);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk House Maker',752);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Powerbod',753);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('First Choice Garden Maintenance',754);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Flying Bear',755);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Parade of Shoes',756);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gold Leaf Garden Management',757);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Anderson-Little',758);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Handy Dan',759);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('LaBelle''s',760);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crandall''s Fine Furniture',761);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Showbiz Pizza Place',762);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Knox Lumber',763);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kiddie City',764);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Office Warehouse',765);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Zantigo',766);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('CSK Auto',767);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Federated Group',768);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('ABCO Foods',769);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Accord Investments',770);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Afforda',771);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Great Clothes',772);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Franklin Simon',773);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr. D''s IGA',774);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Channel Home Centers',775);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Better Business Ideas and Services',776);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nedick''s',777);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Landskip Yard Service',778);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mr. Steak',779);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Musicland',780);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hudson''s MensWear',781);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Spaceage Stereo',782);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Grade A Investment',783);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sound Advice',784);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The White Swan',785);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Elek-Tek',786);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gamma Grays',787);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crown Books',788);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thalhimers',789);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Simply Save',790);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hills Supermarkets',791);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('ABC Markets',792);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Micro Design',793);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Network Air',794);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('J. Riggings',795);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Specialty Restaurant Group',796);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Quality',797);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Smitty''s Marketplace',798);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Huffman and Boyle',799);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Architectural Designs',800);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rogersound Labs',801);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Custom Lawn Service',802);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Glicks Furniture',803);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Record Bar',804);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Asian Plan',805);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Original House of Pies',806);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('New World Realty',807);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Reliable Investments',808);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pergament Home Centers',809);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Roadhouse Grill',810);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wealthy Ideas',811);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Pink Pig Tavern',812);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Carl Durfees',813);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Luria''s',814);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Handy Andy',815);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Carrols Restaurant Group',816);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Schaak Electronics',817);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Boston Sea Party',818);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strategic Profit',819);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Coffey''s Market',820);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thom McAn Store',821);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Payless Cashways',822);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Solution Realty',823);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Netcore',824);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Witmark',825);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Square Circle',826);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Realty',827);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sampson''s',828);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('DGS VolMAX',829);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('John M. Smyth''s Homemakers',830);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('ManPower',831);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pak and Save',832);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wellby',833);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Sample',834);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro Yard Services',835);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Steak and Ale',836);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Idea Infinity',837);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Marianne',838);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bloom Brothers Furniture',839);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Strength Gurus',840);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Titania',841);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Licorice Pizza',842);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sunflower Market',843);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Corinthian Designs',844);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sun Foods',845);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big Apple',846);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Allied Radio',847);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Al''s Auto Parts',848);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Erlebacher''s',849);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Future Plan',850);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Ideal Garden Management',851);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Four Leaf Clover',852);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('McDuff',853);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stratagee',854);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Carter''s Foods',855);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Architectural Genie',856);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big Bear Stores',857);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('K''s Merchandise',858);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hughes & Hatcher',859);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Source',860);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bay Furniture',861);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro Property Maintenance',862);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Big Star Markets',863);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Happy Family',864);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bumper to Bumper Auto Parts',865);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Reliable Guidance',866);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Good Times',867);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gold Medal',868);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Vitamax Health Food Center',869);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Castro Convertibles',870);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cavages',871);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Benesome',872);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('County Seat',873);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('One-Up Realty',874);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('H.C. Bohack',875);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tianguis',876);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Adaptaz',877);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Newmark & Lewis',878);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Olson''s Market',879);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Erb Lumber',880);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Northern Star',881);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('LoRay',882);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('S&W Cafeteria',883);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sun Television and Appliances',884);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Foot Quarters',885);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chatham',886);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fretter',887);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Britches of Georgetown',888);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Consumers Food and Drug',889);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Life Map Planners',890);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Seamans Furniture',891);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tradewell',892);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rainbow Records',893);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Indiewealth',894);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Richman Brothers',895);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Afterthoughts',896);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Access Asia',897);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cherry & Webb',898);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sears Homelife',899);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Libera',900);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Oranges Records & Tapes',901);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Coon Chicken Inn',902);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Konsili',903);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Universal Design Partners',904);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Casa Bonita',905);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Father & Son',906);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chief Auto Parts',907);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Total Sources',908);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mervyn''s',909);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Brand Names',910);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magna Consulting',911);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hill-Behan',912);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Piccolo Mondo',913);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('A Plus Lawn Care',914);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('FamilyMart',915);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chargepal',916);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Quality Realty Service',917);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Superior Interactive',918);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dubrow''s Cafeteria',919);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bonanza Produce Stores',920);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cardinal Stores',921);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro Star Garden Management',922);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Laughner''s Cafeteria',923);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Larry''s Markets',924);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Profitpros',925);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Town and Country Convenience Stores',926);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gas Zone',927);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crafts & More',928);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Superstore',929);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Intelacard',930);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fresh Start',931);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Simple Solutions',932);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rainbow Life',933);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Murray''s Discount Auto Stores',934);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Play Town',935);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Music Den',936);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Electronic Geek',937);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stratabiz',938);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Flipside Records',939);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Integra Wealth',940);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Wall',941);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Bennett Brothers',942);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Auto Palace',943);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Brilliant Home Designs',944);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('American Appliance',945);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('E.J. Korvette',946);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cougar Investment',947);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kenny Rogers Roasters',948);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('WWW Realty',949);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('HomeBase',950);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Signa Air',951);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Druther''s',952);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('World Radio',953);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Golf Augusta Pro Shops',954);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Movie Gallery',955);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Paul''s Food Mart',956);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kleinhans',957);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Naugles',958);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Suadela Investment',959);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rogers Peet',960);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sounds of Soul Records & Tapes',961);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Auto Works',962);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Burger Chef',963);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Shoe Town',964);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Earthworks Yard Maintenance',965);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wholesale Club Inc.',966);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Golden Joy',967);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Allied City Stores',968);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Joshua Doore',969);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Music Boutique',970);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Omni Tech',971);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Destiny Realty',972);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Crown Auto Parts',973);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Morville',974);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Susie''s Casuals',975);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Evans',976);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Heilig-Meyers',977);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Megatronic Plus',978);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Leath Furniture',979);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Weenie Beenie',980);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('David Weis',981);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Britling Cafeterias',982);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Woolf Brothers',983);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gottschalks',984);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Home Quarters Warehouse',985);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dahlkemper''s',986);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mission Realty',987);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('G.I. Joe''s',988);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rolling Thunder',989);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Gas Depot',990);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thriftway Food Mart',991);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cloth World',992);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Camelot Music',993);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Newhair',994);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('A+ Investments',995);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Helios Air',996);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cuppy''s Coffee',997);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('VitaGrey',998);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('House Of Denmark',999);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pantry Pride',1000);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magna Wealth',1001);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Body Fate',1002);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sportswest',1003);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Henry''s',1004);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jeans Unlimited',1005);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Checker Auto Parts',1006);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Muirhead''s',1007);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Warehouse Club Inc.',1008);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Incredible Universe',1009);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Custom Sound',1010);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Karl''s Shoes',1011);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wise Solutions',1012);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cal Stereo',1013);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Rack N Sack',1014);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Balanced Fortune',1015);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Fellowship Investments',1016);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Tape World',1017);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Food Fair',1018);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kinney Shoes',1019);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Network Chef',233);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Vitagee',237);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Infinity Investment Plan',239);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Copeland Sports',244);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Specific Appraisals',248);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('American Wholesale Club',252);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dun Rite Lawn Maintenance',258);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Briazz',264);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kragen Auto Parts',265);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Judy''s',269);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mars Music',270);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Parklane Hosiery',273);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dick Fischers',276);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Nickerson Farms',279);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Honest Air Group',283);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Flexus',287);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Vibrant Man',288);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Chi-Chi''s',290);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pay ''N Pak',292);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('EXPO Design Center',295);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('P. Samuels Men''s Clothiers',299);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Finast',305);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Thrift Auto Parts',307);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monk House Sales',311);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Lazysize',314);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Magna Architectural Design',316);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mission G',322);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Quest Technology Service',324);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Millenia Life',330);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Pro Garden Management',333);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mansmann''s Department Store',338);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Incluesiv',345);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Buckeye Furniture',347);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Quality Event Planner',558);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Team Uno',563);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Mode O''Day',565);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Dun Rite Lawn Care',567);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Netcom Business Services',572);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('House 2 Home',577);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Terra',580);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('The Happy Bear',581);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Hastings',584);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Young @ Heart',586);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Kent''s',589);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Childs Restaurants',590);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Jack Lang',595);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Cut Rite Lawn Care',597);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Robinson Furniture',601);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Official All Star Café',605);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Desmonds Formal Wear',611);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Superior Interior Design',616);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Alladin''s Lamp',621);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Farrell''s Ice Cream Parlour',625);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('FlowerTime',631);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Unity Frankford Stores',633);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Warner Brothers Studio Store',639);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Wetson''s',646);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Planet Profit',647);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Team Designers and Associates',650);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Soft Warehouse',657);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sagebrush',661);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Price Club',663);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sure Save',665);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Solution Bridge',667);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Scotty''s Builders Supply',670);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('HouseWorks!',676);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sky High Financial Advice',679);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Widdmann',685);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Stop N Shop',686);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Monit',689);
Insert into TESTDB.COMPANY (COMPANY,COMPANYID) values ('Sports Unlimited',690);
